//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Multimedia()
        {
            this.Description = "";
            this.Event = "";
            this.Deleted = false;
            this.AdditionalLabels = "";
            this.People = new HashSet<Person>();
            this.Locations = new HashSet<Location>();
        }
    
        public int Id { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string Event { get; set; }
        public Weather Weather { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Deleted { get; set; }
        public string AdditionalLabels { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
