//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Model
{
    using System;
    
    public enum Weather : byte
    {
        Sunny = 0,
        Cloudy = 1,
        PartlyCloudy = 2,
        Rainy = 3,
        Snowy = 4,
        Sleeting = 5,
        Stormy = 6,
        Lightning = 7,
        Thunderous = 8,
        Hailing = 9,
        Windy = 10,
        Foggy = 11,
        Icy = 12,
        None = 13
    }
}
