//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMyPhotos
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationDTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.DTO", IsReference=true)]
    public partial class LocationDTO : object
    {
        
        private int IdField;
        
        private System.Nullable<decimal> LatitudeField;
        
        private System.Nullable<decimal> LongitudeField;
        
        private ServiceReferenceMyPhotos.MultimediaDTO MultimediaField;
        
        private int MultimediaIdField;
        
        private string NameField;
        
        private string SceneryField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceMyPhotos.MultimediaDTO Multimedia
        {
            get
            {
                return this.MultimediaField;
            }
            set
            {
                this.MultimediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MultimediaId
        {
            get
            {
                return this.MultimediaIdField;
            }
            set
            {
                this.MultimediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scenery
        {
            get
            {
                return this.SceneryField;
            }
            set
            {
                this.SceneryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultimediaDTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.DTO", IsReference=true)]
    public partial class MultimediaDTO : object
    {
        
        private string AdditionalLabelsField;
        
        private System.DateTime DateAddedField;
        
        private System.DateTime DateCreatedField;
        
        private System.DateTime DateModifiedField;
        
        private bool DeletedField;
        
        private string DescriptionField;
        
        private string EventField;
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReferenceMyPhotos.LocationDTO> LocationsField;
        
        private string PathField;
        
        private System.Collections.Generic.List<ServiceReferenceMyPhotos.PersonDTO> PeopleField;
        
        private ServiceReferenceMyPhotos.WeatherDTO WeatherField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalLabels
        {
            get
            {
                return this.AdditionalLabelsField;
            }
            set
            {
                this.AdditionalLabelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded
        {
            get
            {
                return this.DateAddedField;
            }
            set
            {
                this.DateAddedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceMyPhotos.LocationDTO> Locations
        {
            get
            {
                return this.LocationsField;
            }
            set
            {
                this.LocationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceMyPhotos.PersonDTO> People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceMyPhotos.WeatherDTO Weather
        {
            get
            {
                return this.WeatherField;
            }
            set
            {
                this.WeatherField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.DTO", IsReference=true)]
    public partial class PersonDTO : object
    {
        
        private System.Nullable<short> AgeField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private ServiceReferenceMyPhotos.MultimediaDTO MultimediaField;
        
        private int MultimediaIdField;
        
        private ServiceReferenceMyPhotos.PhotoDTO PhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceMyPhotos.MultimediaDTO Multimedia
        {
            get
            {
                return this.MultimediaField;
            }
            set
            {
                this.MultimediaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MultimediaId
        {
            get
            {
                return this.MultimediaIdField;
            }
            set
            {
                this.MultimediaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceMyPhotos.PhotoDTO Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherDTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.DTO")]
    public enum WeatherDTO : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunny = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cloudy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartlyCloudy = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rainy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Snowy = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sleeting = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stormy = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lightning = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thunderous = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hailing = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Windy = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Foggy = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Icy = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoDTO", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.DTO", IsReference=true)]
    public partial class PhotoDTO : object
    {
        
        private int HeightField;
        
        private int IdField;
        
        private ServiceReferenceMyPhotos.PersonDTO PersonField;
        
        private int WidthField;
        
        private int XField;
        
        private int YField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceMyPhotos.PersonDTO Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMyPhotos.IMyPhotosService")]
    public interface IMyPhotosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetLocationById", ReplyAction="http://tempuri.org/ILocation/GetLocationByIdResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMyPhotos.LocationDTO> GetLocationByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/AddLocation", ReplyAction="http://tempuri.org/ILocation/AddLocationResponse")]
        System.Threading.Tasks.Task<bool> AddLocationAsync(int multimediaId, ServiceReferenceMyPhotos.LocationDTO locationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/UpdateLocation", ReplyAction="http://tempuri.org/ILocation/UpdateLocationResponse")]
        System.Threading.Tasks.Task<bool> UpdateLocationAsync(ServiceReferenceMyPhotos.LocationDTO locationDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/RemoveLocations", ReplyAction="http://tempuri.org/ILocation/RemoveLocationsResponse")]
        System.Threading.Tasks.Task RemoveLocationsAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/RemovePeople", ReplyAction="http://tempuri.org/IPerson/RemovePeopleResponse")]
        System.Threading.Tasks.Task RemovePeopleAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/AddPerson", ReplyAction="http://tempuri.org/IPerson/AddPersonResponse")]
        System.Threading.Tasks.Task<bool> AddPersonAsync(int multimediaId, ServiceReferenceMyPhotos.PersonDTO personDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/UpdatePerson", ReplyAction="http://tempuri.org/IPerson/UpdatePersonResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonAsync(ServiceReferenceMyPhotos.PersonDTO personDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/AddMultimedia", ReplyAction="http://tempuri.org/IMultimedia/AddMultimediaResponse")]
        System.Threading.Tasks.Task AddMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/GetMultimediaById", ReplyAction="http://tempuri.org/IMultimedia/GetMultimediaByIdResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMyPhotos.MultimediaDTO> GetMultimediaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/GetEveryMultimedia", ReplyAction="http://tempuri.org/IMultimedia/GetEveryMultimediaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceMyPhotos.MultimediaDTO>> GetEveryMultimediaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/UpdateMultimedia", ReplyAction="http://tempuri.org/IMultimedia/UpdateMultimediaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMyPhotos.MultimediaDTO> UpdateMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/FlagMultimediaAsDeleted", ReplyAction="http://tempuri.org/IMultimedia/FlagMultimediaAsDeletedResponse")]
        System.Threading.Tasks.Task FlagMultimediaAsDeletedAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultimedia/UpdateWholeMultimedia", ReplyAction="http://tempuri.org/IMultimedia/UpdateWholeMultimediaResponse")]
        System.Threading.Tasks.Task UpdateWholeMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMyPhotosServiceChannel : ServiceReferenceMyPhotos.IMyPhotosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MyPhotosServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMyPhotos.IMyPhotosService>, ServiceReferenceMyPhotos.IMyPhotosService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhotosServiceClient() : 
                base(MyPhotosServiceClient.GetDefaultBinding(), MyPhotosServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMyPhotosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhotosServiceClient.GetBindingForEndpoint(endpointConfiguration), MyPhotosServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhotosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhotosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMyPhotos.LocationDTO> GetLocationByIdAsync(int id)
        {
            return base.Channel.GetLocationByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddLocationAsync(int multimediaId, ServiceReferenceMyPhotos.LocationDTO locationDTO)
        {
            return base.Channel.AddLocationAsync(multimediaId, locationDTO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateLocationAsync(ServiceReferenceMyPhotos.LocationDTO locationDTO)
        {
            return base.Channel.UpdateLocationAsync(locationDTO);
        }
        
        public System.Threading.Tasks.Task RemoveLocationsAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO)
        {
            return base.Channel.RemoveLocationsAsync(multimediaDTO);
        }
        
        public System.Threading.Tasks.Task RemovePeopleAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO)
        {
            return base.Channel.RemovePeopleAsync(multimediaDTO);
        }
        
        public System.Threading.Tasks.Task<bool> AddPersonAsync(int multimediaId, ServiceReferenceMyPhotos.PersonDTO personDTO)
        {
            return base.Channel.AddPersonAsync(multimediaId, personDTO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePersonAsync(ServiceReferenceMyPhotos.PersonDTO personDTO)
        {
            return base.Channel.UpdatePersonAsync(personDTO);
        }
        
        public System.Threading.Tasks.Task AddMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO)
        {
            return base.Channel.AddMultimediaAsync(multimediaDTO);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMyPhotos.MultimediaDTO> GetMultimediaByIdAsync(int id)
        {
            return base.Channel.GetMultimediaByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferenceMyPhotos.MultimediaDTO>> GetEveryMultimediaAsync()
        {
            return base.Channel.GetEveryMultimediaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMyPhotos.MultimediaDTO> UpdateMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO)
        {
            return base.Channel.UpdateMultimediaAsync(multimediaDTO);
        }
        
        public System.Threading.Tasks.Task FlagMultimediaAsDeletedAsync(int id)
        {
            return base.Channel.FlagMultimediaAsDeletedAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateWholeMultimediaAsync(ServiceReferenceMyPhotos.MultimediaDTO multimediaDTO)
        {
            return base.Channel.UpdateWholeMultimediaAsync(multimediaDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotosService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotosService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MyPhotosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMyPhotosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MyPhotosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMyPhotosService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMyPhotosService,
        }
    }
}
